### ISSUE TITLE
Enhance startup speed with commands not work

### ISSUE THREAD

**Issue by JinraeKim** [fannheyward/coc-julia#131]
It's an issue similar to #16.

I've tried `:CocInstall coc-julia julia.CompileLanguageServerBin julia.CompileLanguageServerSysimg` but encountered the following error.

Looks like an npm error but I don't have a background of it.
```
Install finished

- ✓ coc-julia Installed extension coc-julia@0.7.0 at /Users/jinrae/.config/coc/extensions/node_modules/coc-julia
- ✗ julia.CompileLanguageServerBin Bad response from https://registry.npmjs.org/julia.CompileLanguageServerBin: 404
- ✗ julia.CompileLanguageServerSysimg Bad response from https://registry.npmjs.org/julia.CompileLanguageServerSysimg: 404
```
For more details, see the below picture (sorry for uploading a picture; I don't know how to copy-and-paste the pop-up message).
![image](https://user-images.githubusercontent.com/43136096/109256581-98629a80-7839-11eb-8956-ca105504d213.png)

**Comment by JinraeKim** [comment]
I'm not sure but `https://registry.npmjs.org/` gives me a message like this.
```
{"db_name":"registry","engine":"couch_bt_engine","doc_count":2003050,"doc_del_count":335,"update_seq":6811600,"purge_seq":0,"compact_running":false,"sizes":{"active":35675565705,"external":113206970966,"file":35779952880},"disk_size":35779952880,"data_size":35675565705,"other":{"data_size":113206970966},"instance_start_time":"1614069908856785","disk_format_version":7,"committed_update_seq":6811600,"compacted_seq":6811154,"uuid":"f7fe587f4e4770466ccd76072de1c901"}
```

**Comment by fannheyward** [comment]
It's `:CocInstall coc-julia` to install this extension.

Run `:CocCommand julia.CompileLanguageServerSysimg` to build sysimg after you installed coc-julia.

**Comment by JinraeKim** [comment]
@fannheyward thanks a lot :)
