### ISSUE TITLE
Confusion on how to install

### ISSUE THREAD

**Issue by jambo6** [fannheyward/coc-julia#152]
Hello,

Apologies but I am having some confusion with how to install this, is `:CocInstall coc-julia` supposed to mean this works right out of the box? I have tried this and just receive `[coc.nvim] Can't find julia` whenever I open a `.jl` file. 

I have also tried adding the following to my `CocConfig` json file
```
{
   "languageserver":{
      "julia":{
         "command":"julia",
         "args":[
            "--startup-file=no",
            "--history-file=no",
            "-e",
            "using LanguageServer, Pkg, Sockets, SymbolServer; env_path = dirname(Pkg.Types.Context().env.project_file); server = LanguageServer.LanguageServerInstance(stdin, stdout, true, env_path, \"\"); server.runlinter = true; run(server);"
         ],
         "filetypes":[
            "julia"
         ]
      }
    }
}
```
which returns `[coc.nvim] Sever languageserver.julia failed to start: Launching server "languageserver.julia" using command julia failed`

However when I run the command in full in terminal it appears to start a server no problem.

**Comment by fannheyward** [comment]
You need to have Julia been installed and `julia` command in your `$PATH`.

If you're using coc-julia, you don't need to set Julia language server in `CocConfig` any more.
