### ISSUE TITLE
Incorrect completion if the typed fragment does not match the completion item

### ISSUE THREAD

**Issue by lassepe** [fannheyward/coc-julia#163]
In an emtpy `.jl` file,  when I type `data` (note the lowercase) and trigger completion using `TAB` to complete the builtin `DataType`, the completion is inserted but the first bit that I already types is not replaced. Thus, I get `dataDataType` as a completion. This does not happen when the letters that I already typed have the correct case, e.g. `Data<TAB>` yields `DataType` as expected.

**Comment by lassepe** [comment]
Update: this also seems to happen in a view other cases where the fragment of the word typed does match the item that will be completed. E.g. if you type `szs` to get completion for `set_zero_submnormals` the completion results in `szsset_zero_subnormals
`.

**Comment by pfitzseb** [comment]
FWIW, LanguageServer.jl is correctly specifying the text range that should be modified, at least as far as I can tell (as evidenced by completions working properly in VSCode).

**Comment by fannheyward** [comment]
Try v0.8.1.

**Comment by lassepe** [comment]
Thank you @fannheyward. v0.8.1 seems to fix this issue.

**Comment by oblitum** [comment]
Regarding completion weirdness, I still hit this:

![gif-2021-05-11-111230](https://user-images.githubusercontent.com/1269815/117830343-ec322c80-b249-11eb-8e47-760ab3ec766b.gif)

**Comment by lassepe** [comment]
Interesting. I am seeing the same completion weirdness. Only for `import` though. I did not notice a similar behavior for other variable names or keywords.

**Comment by fannheyward** [comment]
Try v0.8.3

**Comment by oblitum** [comment]
`import` completion is fixed now. thx.

**Comment by fannheyward** [comment]
The keyword completion issue like `import` has been fixed in LanguageServer.jl https://github.com/julia-vscode/LanguageServer.jl/pull/937, coc-julia will remove the fix.

**Comment by fannheyward** [comment]
The fix in coc-julia can work with old and latest LanguageServer.jl, I'll keep it and remove in later.

**Comment by lassepe** [comment]
While this seems to be fixed for most cases, there is still oddity in file path completion:

![Peek 2021-05-17 12-23](https://user-images.githubusercontent.com/10076790/118473991-dec5e800-b70a-11eb-9178-179fb2e195ab.gif)

**Comment by fannheyward** [comment]
@pfitzseb same issue as `import`.

**Comment by fannheyward** [comment]
@lassepe v0.8.6 adds a small hack for this, please try it.

**Comment by lassepe** [comment]
Wow, that was quick. Thank you @fannheyward  for the quick fix. Though I guess this should be fixed upstream? Should I file an issue with LanguageServer.jl?

**Comment by fannheyward** [comment]
@lassepe I've pinged @pfitzseb already, it's a same issue as keyword completion.

**Comment by pfitzseb** [comment]
Ok, with https://github.com/julia-vscode/LanguageServer.jl/pull/938 I hopefully got all completions fixed ;)
