### ISSUE TITLE
vscjlsymserv files in project directory

### ISSUE THREAD

**Issue by tpoisot** [fannheyward/coc-julia#233]
This issue was already raised in #57 - basically, whenever the LanguageServer starts, this creates a pipe in the working directory.

I have checked by deactivating JuliaFormatter, and it looks like `coc-julia` is what creates these files.

**Comment by fannheyward** [comment]
The `vscjlsymserv-xxx` file is created by SymbolServer.jl,  https://github.com/julia-vscode/SymbolServer.jl/blob/e4865c09cb2a4dbe60b95802826501d0b2986b1d/src/SymbolServer.jl#L72

Do you use Windows or Linux/macOS? The file should be located in your system tmp folder.

**Comment by lassepe** [comment]
FWIW, I'm using Linux and I'm having the same problem as pointed out in the issue linked above. Maybe some part of the pipeline sets one of these environment variables?

```julia
help?> tempdir()
  tempdir()

  Gets the path of the temporary directory. On Windows, tempdir() uses the first environment variable found in the ordered list TMP, TEMP, USERPROFILE. On all other operating systems, tempdir() uses the first
  environment variable found in the ordered list TMPDIR, TMP, TEMP, and TEMPDIR. If none of these are found, the path "/tmp" is used.
```

**Comment by lassepe** [comment]
In fact, if I explicitly launch vim with `TMPDIR=/tmp nvim` then I'm not getting these artifacts in my project directory anymore and they are created in `/tmp` instead.

**Comment by fannheyward** [comment]
@lassepe what's your coc.nvim version? What's your `:CocInfo`?

**Comment by lassepe** [comment]
```
vim version: NVIM v0.5.0
node version: v16.4.2
coc.nvim version: 0.0.80-19ead882b9
coc.nvim directory: /home/lassepe/dotfiles/dotfiles/config/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux
```

**Comment by fannheyward** [comment]
1. launch `nvim`, what's the output of `:echo eval('$TMPDIR')`?
2. `TMPDIR=/tmp nvim`, what's the output now?

**Comment by lassepe** [comment]
Nothing for 1; `/tmp` for 2. I guess a quick-fix would be to just add `export TMPDIR=/tmp` in my `~/.profile`.

**Comment by fannheyward** [comment]
In my tests, 1 will output something like `/var/folders/bq/sdn5qctj37b3wgx_bnwfgmfm0000gp/T/`. I'll make a fix for this.

**Comment by fannheyward** [comment]
Try v0.9.1

**Comment by lassepe** [comment]
That does the trick, thanks!

**Comment by tpoisot** [comment]
Fantastic!
