### ISSUE TITLE
Undocumented `julia-*` config options?

### ISSUE THREAD

**Issue by iago-lito** [fannheyward/coc-julia#252]
I'm surprised to read only two configuration options on this repo's README, but I read from coc autocompletion in my `coc-settings.json` that `julia.*` yields many more config options.. are they really provided by this extension? Where are they documented?

**Comment by fannheyward** [comment]
> only two configuration options on this repo's README

The two are not configuration options, they're command.

> are they really provided by this extension?

Yes, they're provided by coc-julia, you can get them all from https://github.com/fannheyward/coc-julia/blob/master/package.json#L53.

I'm a little lazy to document them in README 😵‍💫, will update ASAP.
