### ISSUE TITLE
Numerous "Missing reference" warnings even with `"julia.lint.missingrefs": false`.

### ISSUE THREAD

**Issue by iago-lito** [fannheyward/coc-julia#253]
For instance with this in `coc-settings.json`:
```
    "julia.environmentPath": ".",
    "julia.lint.missingrefs": false,
```
and the following simple file:
```julia
using Revise             Missing reference: Revise
```
Although `using Revise` yields no error in a REPL opened in the same folder.

**Comment by lassepe** [comment]
Maybe Revise is not part of your Project.toml but only available through some other environment in the stack?

**Comment by iago-lito** [comment]
@lassepe Hm, in this case, would the repl not error when I try `using Revise`? Anyway, the message still appears on whatever reference I use from my local package. Does the julia LSP server actually `activate`s my current environment?

(I'm still struggling to construct a mwe, because I'm not familiar with Julia yet.)

**Comment by iago-lito** [comment]
I can reproduce with a fresh package:

In an empty folder:
```
$ julia
julia> using PkgSkeleton
julia> PkgSkeleton.generate("empty_package")
...
successfully generated empty_package
```
then `cd empty_package` and setup `src/empty_packages.jl`
```julia
module empty_package

function f()
    println("Hey")
end

end # module
```
then when editing `empty_package/main.jl`
```julia
using empty_package         Missing reference: empty_package

empty_package.f()           Missing reference: empty_package
```

**Comment by lassepe** [comment]
coc-nvim should activate the current project. But for that to work you need to be inside the directory I belief. Did you launch nvim within `empty_package` in your example above?

**Comment by iago-lito** [comment]
Yeah, I was within `empty_package` folder and opened file with `nvim main.jl`.

**Comment by iago-lito** [comment]
Closing as I cannot reproduce anymore :)
