### ISSUE TITLE
coc-julia vs julia-vscode?

### ISSUE THREAD

**Issue by colinxs** [fannheyward/coc-julia#26]
The julia-vscode extension makes things simple by bundling it's julia dependencies, running with it's own isolated depot, etc. In the future, they plan to ship a precompiled version (e.g. #16). Rather than duplicating all of that effort here, what do you think of making coc-julia a wrapper around julia-vscode? This may also help avoid issues like https://github.com/julia-vscode/LanguageServer.jl/issues/651.

Thoughts?

**Comment by fannheyward** [comment]
closes by https://github.com/fannheyward/coc-julia/commit/623ae982b51f2f60653b4e2bd2d64267d45db1cd
