### ISSUE TITLE
coc-julia does not start

### ISSUE THREAD

**Issue by andevellicus** [fannheyward/coc-julia#27]
Julia 1.4
NVIM v0.4.4
coc.nvim version: 0.0.78-bdd9a9e140

I get a LanguageServer startup error:
```
syntax: "/" is not a unary operator
```

I believe it's a problem with:
```
server = LanguageServer.LanguageServerInstance(stdin, stdout, debug, env_path, "")
```

Seems like this was a recent change.

**Comment by fannheyward** [comment]
This change has been reverted, please `:CocUpdate` to coc-julia v0.1.3.
