### ISSUE TITLE
Leave server running when I leave neovim?

### ISSUE THREAD

**Issue by iago-lito** [fannheyward/coc-julia#275]
Julia language server is especially long to start because it needs to compile everything on first use.
Can I configure coc-julia so that the server does not stop when I leave neovim, and my future neovim instances attach to the same running server?

**Comment by fannheyward** [comment]
No, this needs the language server to support daemon running, coc-julia can't do this.

You can run `:CocCommand julia.CompileLanguageServerSysimg` to build the language server sysimg, this will speedup the LS launching.
