### ISSUE TITLE
Format options in configurations do not work

### ISSUE THREAD

**Issue by zhangqian-sh** [fannheyward/coc-julia#305]
I have installed the plugin and the formatter works by calling CocAction('format'). But it seems that the default indent size of the formatter is 8 and I cannot change it by setting"julia.format.indent" to 4. Even more, I have tried to turn off some other formatting options, but none of them takes effect. My Julia version is 1.7.2.

**Comment by fannheyward** [comment]
The configurations are outdated, you should use `.JuliaFormatter.toml`:

```toml
indent = 8
```

- https://github.com/julia-vscode/julia-vscode/pull/2334
- https://github.com/julia-vscode/LanguageServer.jl/pull/1028
- https://domluna.github.io/JuliaFormatter.jl/stable/config/#Basic-Configuration
