### ISSUE TITLE
how support JuliaFormatter

### ISSUE THREAD

**Issue by beamiter** [fannheyward/coc-julia#308]
currently, no support for format

**Comment by lassepe** [comment]
Formatting should "just work" out of the box as JuliaFormatter is integrated in the language server already. All you should have to do is add keybinding to your vim rc, e.g.:

```vim
" Formatting selected code.
xmap <silent><leader>f <Plug>(coc-format-selected)
nmap <silent><leader>f :call CocActionAsync('format')<CR>
```

**Comment by fannheyward** [comment]
Try `:call CocActionAsync('format')`.

**Comment by beamiter** [comment]
thanks a lot.
