### ISSUE TITLE
`coc#status()` frozen at indexing packages

### ISSUE THREAD

**Issue by carlocab** [fannheyward/coc-julia#33]
I have my statusline set to show me the output of `coc#status()`. After the Julia language server starts, at some point `coc#status()` says `Julia Language Server Indexing packages...`, and stays frozen there.

I decide to leave it overnight to see if it will finish, but it hasn't. I suspect the language server isn't actually doing anything, because `htop` reports `0.0` in the `CPU%` column for the language server process.

Is this a bug in `coc#status`?

**Comment by fannheyward** [comment]
Not a bug of `coc#status`. The progress message is came from Julia Language Server, tested with VSCode + Julia LS:

```
Received request 'window/workDoneProgress/create - (7eb45c41-fd70-4e34-adf5-55397a222856)'.
Params: {
    "token": "e6b544d9-3d17-4d9f-bdb0-44e1568e8072"
}

Received notification '$/progress'.
Params: {
    "token": "e6b544d9-3d17-4d9f-bdb0-44e1568e8072",
    "value": {
        "kind": "begin",
        "title": "Julia Language Server",
        "message": "Indexing packages..."
    }
}

Received notification '$/progress'.
Params: {
    "token": "e6b544d9-3d17-4d9f-bdb0-44e1568e8072",
    "value": {
        "kind": "end"
    }
}
```

As you see, client has received `begin` -> `end` progress message, and client hides the status message.

But in coc + coc-julia:

```
Received request 'window/workDoneProgress/create - (e7fb66ef-03e2-46e3-9476-736fb904d2d7)'.
Params: {
    "token": "fc23c7c5-f4d8-46ab-abbd-b49897cf11a3"
}

Received notification '$/progress'.
Params: {
    "token": "fc23c7c5-f4d8-46ab-abbd-b49897cf11a3",
    "value": {
        "kind": "begin",
        "title": "Julia Language Server",
        "message": "Indexing packages..."
    }
}
```

There is no `end` progress message, the client doesn't hide the status line message.

I'll continue to trace this.

**Comment by carlocab** [comment]
Strange. Thanks for looking into it.

**Comment by fannheyward** [comment]
Try coc-julia v0.4.0

**Comment by carlocab** [comment]
I'm seeing this issue again. Can we reopen this, or would you like me to open a new issue?

**Comment by fannheyward** [comment]
@carlocab you can open a new issue with more info, such as your coc-julia version, coc version, how to reproduce etc.
