### ISSUE TITLE
Tag system image with julia version

### ISSUE THREAD

**Issue by lassepe** [fannheyward/coc-julia#343]
Currently, coc-julia stores a "global" system image in `coc-julia-data/sysimg`. When the user upgrades to a new julia version and forgets to delete this system image, the server crashes without any informative error. A simple fix may be to store the system image with the corresponding julia version in the file name. This way, coc-julia can automatically detect that there is no valid system image for the current version. This would also make it easier for users to switch between different julia versions.

**Comment by fannheyward** [comment]
coc-julia 0.13.0 will compile sysimg with Julia version to `coc-julia-data/sysimg-1.7.0` etc. At server launching, coc-julia will use the Julia version paired sysimg-x.y.z to run.
