### ISSUE TITLE
Jump to other files no longer works

### ISSUE THREAD

**Issue by lassepe** [fannheyward/coc-julia#359]
As of 0.13, `<Plug>(coc-definition)` no longer works when invoked on file names. For variables and functions it still works but invoking it on something like `include("foo.jl")` it always fails with "definition not found".

**Comment by fannheyward** [comment]
Reproduced, client sends `textDocument/definition` but LanguageServer.jl returns empty results. Have no idea about this, still working on this.

**Comment by fannheyward** [comment]
Tested with LanguageServer.jl 4.2.0, works as expected.

```

[Trace - 09:18:32] Sending request 'textDocument/definition - (2)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fannheyward/src/DJulia/src/DJulia.jl"
    },
    "position": {
        "line": 2,
        "character": 9
    }
}


[Trace - 09:18:32] Received response 'textDocument/definition - (1)' in 216ms.
Result: [
    {
        "uri": "file:///Users/fannheyward/src/DJulia/src/foo.jl",
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 0
            }
        }
    }
]
```

But with 4.3.1:

```
[Trace - 09:19:53] Sending request 'textDocument/definition - (2)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fannheyward/src/DJulia/src/DJulia.jl"
    },
    "position": {
        "line": 2,
        "character": 9
    }
}


[Trace - 09:19:53] Received response 'textDocument/definition - (1)' in 163ms.
Result: []
```

**Comment by fannheyward** [comment]
Tested with VSCode + Julia extension:

```
[Trace - 09:29:15] Sending request 'textDocument/hover - (46)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fannheyward/src/DJulia/src/DJulia.jl"
    },
    "position": {
        "line": 2,
        "character": 9
    }
}


[Trace - 09:29:15] Received response 'textDocument/hover - (46)' in 3ms.
No result returned.


[Trace - 09:29:17] Sending request 'textDocument/definition - (47)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/fannheyward/src/DJulia/src/DJulia.jl"
    },
    "position": {
        "line": 2,
        "character": 9
    }
}


[Trace - 09:29:17] Received response 'textDocument/definition - (47)' in 1ms.
Result: []
```

Same results...

**Comment by lassepe** [comment]
This seems to have been a deliberate choice. The julia-vscode devs stated on slack that these are document links now. I'm not sufficiently familiar with the internals to figure out how to trigger those events though

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentLink

**Comment by fannheyward** [comment]
You can use `:CocList links` to list all document links in current buffer. Also you can use get links from `CocAction('links')`, this can be used in custom functions.

**Comment by fannheyward** [comment]
Use DocumentLinkProvider for include https://github.com/julia-vscode/LanguageServer.jl/pull/1064

**Comment by lassepe** [comment]
Thanks for the clarification. For future reference for anyone who has the same problem, I added a new keybinding to my config which calls `CocAsyncAction("openLink")`:

```vim
nmap <silent> gl :call CocActionAsync("openLink")<CR>
```
