### ISSUE TITLE
Better package environment search?

### ISSUE THREAD

**Issue by carlocab** [fannheyward/coc-julia#46]
This is somewhat related to, but different from, #45.

As I understand it, coc-julia is currently configured so that `LanguageServer.jl` checks the current working directory for a `Manifest.toml` file from which it indexes the packages in the current environment. This means, for instance, that the Julia LS will not find this file if you are in a subdirectory of your project folder that contains the manifest. Moreover, it seems that it ignores `Project.toml` files, even though `Manifest.toml` can be generated from the project file, which is also more common than the manifest file. (For example, `Manifest.toml` is an entry in the template `.gitignore` for Julia projects.)

Is it possible for coc-julia to employ slightly more sophisticated behaviour regarding this? For example, it could check for `Project.toml` files as well, and do that search in the parent directories of the working directory. As a fallback, it could check `$JULIA_DEPOT_PATH/environments` for directories containing these files. (If this is not set in the user's shell, one can recover this in Julia using `Base.DEPOT_PATH`. The first directory in this path on a nix-like OS is `$HOME/.julia`.)

Is this something that can be implemented in coc-julia? I remember reading that the standard config for the built-in nvim-lsp does something like this, so it seems like it's something configured at the plugin-level. (I can't find the GH issue/PR where I read it, unfortunately, but I'm trying to track it down.)

Thanks again for your time.

**Comment by carlocab** [comment]
I've had a closer look at what coc-julia does when one opens a `.jl` file. It seems it starts Julia with https://github.com/fannheyward/coc-julia/blob/master/server/main.jl, and passes some command-line arguments to `LanguageServerInstance`, which sets the project environment.

You currently have it set to only use the current working directory, which isn't ideal, I think.

However, it seems using `Manifest.toml` instead of `Project.toml` is a limitation of LanguageServer.jl, so probably should be fixed there. I'll follow that part of this issue there.

**Comment by fannheyward** [comment]
Should be fixed in v0.6.0 with #67 , please give it a try.
