### ISSUE TITLE
type highlighting

### ISSUE THREAD

**Issue by AlexanderPerez23** [fannheyward/coc-julia#472]
I want to turn off this setting where the types of every single variable are being printed in line, its slowing my Neovim down considerably and I can't find how to turn this off![Screenshot 2024-06-05 at 9 42 56 AM](https://github.com/fannheyward/coc-julia/assets/84990602/5623ffef-724d-439a-8e9e-baa9416e9aa9)

**Comment by fannheyward** [comment]
Check `:h coc-inlayHint`.
