### ISSUE TITLE
Language server socket in project directory?

### ISSUE THREAD

**Issue by lassepe** [fannheyward/coc-julia#57]
Since the latest release (0.5.1) I am observing that `coc-julia` places a socket (named `vscjlsymserv-<some-UUID>`) in my current working directory. These seem not to get deleted after the session is closed. Is this desired behavior?

**Comment by fannheyward** [comment]
Can't reproduce, coc-julia will not create socket file.

**Comment by lassepe** [comment]
You are absolutely right. It seems to be caused by JuliaFormatter. I am sorry for the confusion.

**Comment by lassepe** [comment]
Actually, I am still seeing the same issue and it does seem to be related to the SymbolServer launched by coc-julia. 
These files seem to correspond to the sockets created [here](https://github.com/julia-vscode/SymbolServer.jl/blob/d1979b5a3097c897d7bb6ab4283e89db714f161c/src/SymbolServer.jl#L69).

I cannot always reproduce this issue but it seems to happen most frequently if I quit nvim with `:cq` (e.g. if I realize that I want to abort editing). Maybe in this case the symbol server is not shut down correctly?

**Comment by fannheyward** [comment]
The `vscjlsymserv-<some-UUID>` file should be in tmp folder, and looks like it's not deleted when Julia LS exit. Have no idea about this.

**Comment by cristobaltapia** [comment]
I also see this files in my working directory. It doesn't bother me too much, but I was wondering where they came from.

**Comment by fannheyward** [comment]
@cristobaltapia this has been fixed in v0.9.1
